# Generated by Django 5.2.2 on 2025-06-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(help_text='e.g. 10:15 AM'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(help_text='e.g. 09:00 AM'),
        ),
    ]
