# Generated by Django 5.2.2 on 2025-06-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_course_end_time_alter_course_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='e.g. 2025-12-15', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='e.g. 2025-09-01', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='YYYY-MM-DD or YYYY-MM-DDTHH:MM[:SS]', null=True),
        ),
    ]
