# Generated by Django 5.2.2 on 2025-06-30 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_course_end_date_course_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('assigned_by', models.CharField(default='auto', help_text='Who assigned this block', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', to='studies.task')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
