# Generated by Django 5.2.2 on 2025-07-27 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_scheduledtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 12, 31), help_text='e.g. 2025-12-15'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 7, 26), help_text='e.g. 2025-09-01'),
        ),
    ]
